### ISSUE TITLE
Create node app with cron job to send emails daily.

### ISSUE THREAD

**Issue by itamark** [itamark/the-daily-method#4]
Related to #3 - we need to create a node app that sends the daily method out to subscribers.

**Comment by pinkasey** [comment]
I suggest instead -
Add push notifications.
I have this app on my phone home-screen, if it could somehow send me push notification every day - that would be great.

Don't know how that works though, i guess you still need backend for that.

**Comment by itamark** [comment]
@pinkasey great idea. Actually, desktop notifications are a thing - and so are push notifications from webapps.
This is also a great idea since it's a much easier MVP to set up than a full mailing system.

**Comment by itamark** [comment]
Closed in favor of push notifications
